language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

cache:
  directories:
    - node_modules

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "us-west-2"
  bucket: gekko-node
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on:
    branch: master

after_deploy:
  - echo "done deploying"

script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
