language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

cache:
  directories:
    - node_modules

before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: &1
    secure: "$AWS_SECRET_KEY"
  local_dir: dpl_cd_upload
  skip_cleanup: true
  bucket: gekko-node
  region: "us-west-2"
  on: &2
    branch: master
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: *1
  bucket: gekko-node
  key: latest.zip
  bundle_type: zip
  application: gekko
  deployment_group: gekkoDeploymentGroup
  region: "us-west-2"
  on: *2

after_deploy:
  - echo "done deploying"
