version: 0.0
os: linux
files:
  - source: ./
    destination: /tmp
permissions:
  - object: /tmp
    pattern: "**/*.sh"
    mode: 777
    owner: ec2-user
    type:
      - file
hooks:
  ApplicationStop:
    - location: ./scripts/kill_container.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    - location: ./load_image.sh
      timeout: 10
      runas: ec2-user
  ApplicationStart:
    - location: ./scripts/start_container.sh
      timeout: 10
      runas: ec2-user
