branch-defaults:
  master:
    environment: gekko-dev
    group_suffix: null
global:
  application_name: gekko
  branch: null
  default_ec2_keyname: ec2-primary
  default_platform: Docker 17.09.1-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
